[package]
name = "desktop-build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
renderer-core = { path = "../../core" }
env_logger = "0.9"
log = "0.4"