[package]
name = "web-build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
renderer-core = { path = "../../core" }
console_log = "0.2"
log = "0.4"
